### ISSUE TITLE
"Curator of the week" feed is not updating on WikiPathways front page

### ISSUE THREAD

**Issue by khanspers** [wikipathways/wikipathways.org#80]
The "Curator of the week" feed is not updating based on the xml its supposed to be using:

https://www.wikipathways.org/index.php/WikiPathways

Its still displaying Alex, even though Alex's name was removed from the xml (as a test). A caching issue?

**Comment by egonw** [comment]
@khanspers,this was fixed since, right?

**Comment by khanspers** [comment]
Nope, its still broken as far as I know, still updating manually.

**Comment by egonw** [comment]
Ah! Oh, sorry to hear that! :(
